[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""

body = """
{% if version %}\
    {% if previous.version %}\
        # [{{ version | trim_start_matches(pat="v") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
    {% else %}\
        # [{{ version | trim_start_matches(pat="v") }}] ({{ timestamp | date(format="%Y-%m-%d") }})
    {% endif %}\
{% else %}\
    # [unreleased]
{% endif %}\

{% macro group_commits(group_name) %}\
    {% for group, commits in commits | group_by(attribute="group") %}\
        {% if group == group_name %}\
            ### {{ group | upper_first }}

            {% for commit in commits %}\
                * {% if commit.scope %}**{{ commit.scope }}:** {% endif %}\
                    {% if commit.breaking %}[**breaking**] {% endif %}\
                    {{ commit.message }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }})) \
                    [@{{ commit.author.name }}](https://github.com/{{ commit.author.name }})
            {% endfor %}

        {% endif %}\
    {% endfor %}\
{% endmacro %}\

{{ self::group_commits(group_name="Bug Fixes") }}\
{{ self::group_commits(group_name="Features") }}\
{{ self::group_commits(group_name="Performance") }}\
{{ self::group_commits(group_name="Refactor") }}\
{{ self::group_commits(group_name="Testing") }}\
{{ self::group_commits(group_name="DevOps") }}\
{{ self::group_commits(group_name="Documentation") }}\
{{ self::group_commits(group_name="Styling") }}\
{{ self::group_commits(group_name="Miscellaneous Tasks") }}\
{{ self::group_commits(group_name="Security") }}\
{{ self::group_commits(group_name="Revert") }}\
\n
"""

footer = """
<!-- Generated by git-cliff. -->
"""

trim = true
postprocessors = []


[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = []

commit_parsers = [
  { message = "^fix", group = "Bug Fixes" },
  { message = "^feat", group = "Features" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^test", group = "Testing" },
  { message = "^ci", group = "DevOps" },
  { message = "^doc", group = "Documentation" },
  { message = "^style", group = "Styling" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^chore", group = "Miscellaneous Tasks" },
  { body = ".*security", group = "Security" },
  { message = "^revert", group = "Revert" },
]

protect_breaking_commits = false
filter_commits = false
topo_order = false
sort_commits = "oldest"
