// Build script for SSR bundle.
// Bundles src/api/render.ts into api/render.js for Vercel Serverless Functions.

import * as esbuild from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';


// Ensure the api directory exists.
await mkdir('api', { recursive: true });

// Create a package.json in api/ to force CommonJS mode.
// This overrides the root package.json's "type": "module".
await writeFile('api/package.json', JSON.stringify({ type: 'commonjs' }, null, 4));

await esbuild.build({
    entryPoints: ['src/api/render.ts'],
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'cjs',
    outfile: 'api/render.js',
    external: [
        // Only keep @vercel/node and local puppeteer external.
        '@vercel/node',
        'puppeteer',
    ],
    banner: {
        js: '// Auto-generated by scripts/build-ssr.mjs. Do not edit directly.\n'
    }
});

console.log('SSR bundle built successfully: api/render.js');
