// Build script for SSR bundle.
// Bundles src/ssr-entry.ts into api/render.js for Vercel Serverless Functions.

import * as esbuild from 'esbuild';
import { mkdir } from 'node:fs/promises';


// Ensure the api directory exists.
await mkdir('api', { recursive: true });

await esbuild.build({
    entryPoints: ['src/api/render.ts'],
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'esm',
    outfile: 'api/render.js',
    external: [
        // Vercel provides these at runtime.
        '@vercel/node',
        // Keep puppeteer external - dynamically imported for local dev only.
        'puppeteer',
        // Puppeteer-core must be available at runtime.
        'puppeteer-core',
        // @sparticuz/chromium-min must be external - it uses CommonJS internally.
        // Vercel will install it from dependencies and provide at runtime.
        '@sparticuz/chromium-min',
    ],
    banner: {
        js: '// Auto-generated by scripts/build-ssr.mjs. Do not edit directly.\n'
    }
});

console.log('SSR bundle built successfully: api/render.js');
